### PR TITLE
Add an error message for missing form fields #39

### PR DESCRIPTION
**Pull request by seann1**
# Checkliste für neue Post
Checkliste mittels der _Live Preview_ abzuhacken:

- [ ] Rechtschreibung mit Copy+Paste in einem Checker geprüft
- [ ] Formattierung & Layout geprüft
- [ ] Sichtbarkeit des Posts geprüft
- [ ] Datum der Veröffentlichung in Dateinamen & Parameter geprüft
- [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
- [ ] [Bilder](https://resizeimage.net/) sind nicht größer als MAXIMAL 300kb & sehen trotzdem gut aus.
- [ ] Die obigen Punkte mit Hilfe der _Live Preview_ gecheckt
_
- [ ] Im Fall eines Blogartikels: Squash-Merge benutzen 

## Allgemeine Hinweise:
- codeklasse nicht Codeklasse
- Lehrkräfte statt Lehrer

I don't speak German, I have added inline JavaScript in _includes/contact-form.html
The code checks for events on the document object and applies the "is-success" and "is-danger" classes to fields of the contact form. If any of the fields are not filled out correctly a message appears below the submit button which says "Bitte füllen Sie alle Felder aus".

### CODE REVIEW

**Comment by s-gbz** [comment]
Hey @seann1 - thanks a lot for your kind & unexpected contribution! :fire: :heart: 
There're two minor points I noticed

- It seems your formatter accidentally went over all project files which is a bit tricky, because I'd have to go over all files to check if a possible modification slipped in
- The validation message only triggers after the form is dirty 
> Each input element has a boolean dirty value flag. The dirty value flag must be initially set to false when the element is created, and must be set to true whenever the user interacts with the control in a way that changes the value.

If you could address those two points it would be hugely appreciated!
Otherwise I'll try to check in later this week and fix those points myself.

PS: Those recent outside contributions are just awesome! :100: :star_struck: 
I'll setup an english PR template & installation guide asap - have you had any noteworthy trouble/ difficulty starting or getting into the project?

**Review by s-gbz — CHANGES_REQUESTED** [review]
^see points above

**Comment by seann1** [comment]
I can submit a new pull request today. I will reset my local repository and copy and paste the JS code I wrote into the file for the contact form. I will turn my formatting extension off so all files aren't altered. I could use some clarification around the boolean dirty flag on the inputs.

You are saying that each input has a "dirty=false" attribute which should be set to true once a user interacts with the input?

**Comment by s-gbz** [comment]
Hey there, that'd be awesome!
image

Jokes aside, what I meant by "dirtying" is that the message is only triggered _after_ some input has been provided.

https://user-images.githubusercontent.com/23424538/151149813-350943d9-cb43-4017-8329-21d73274d027.mp4

It would be cool if it would be triggered earlier, but since I didn't find a "quick hack" googling I guess that it's rather unimportant.

I think resetting the files & providing a "clean" PR would be sufficient :slightly_smiling_face: 
By the way, your portfolio looks really cool! How did you stumble into OSS?

**Comment by seann1** [comment]
> I think resetting the files & providing a "clean" PR would be sufficient 🙂 By the way, your portfolio looks really cool! How did you stumble into OSS?

> Jokes aside, what I meant by "dirtying" is that the message is only triggered _after_ some input has been provided.

I submitted a "clean" PR. The error message is triggered when the submit button is clicked now which I think is the functionality you are looking for.

Thanks! I have been learning React and looking for a software development position. I heard in a meetup I attended that contributing to OSS projects is a good way to build up your resume and learn to collaborate. I found this project here: <https://goodfirstissues.com/>

**Comment by s-gbz** [comment]
Updated in and closed by #44

**Pull request closed without merging**
